CREATE TABLE URL_MAPPING
(
    SHORT_CODE VARCHAR(10) PRIMARY KEY,
    ORIGIN_URL VARCHAR(255),
    HIT_COUNT  INT,
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME
);

CREATE INDEX IX_ORIGIN_URL ON URL_MAPPING (ORIGIN_URL);
